### PR TITLE
Add missing query search terms

### PR DESCRIPTION
**Pull request by rasa**
From https://support.google.com/mail/answer/7190

Example usage:
```python
from simplegmail import Gmail
from simplegmail.query import construct_query

gmail = Gmail()
query_params = {
    "list": "info@example.com",
    "chat": "movie",
    "deliveredto": "username@gmail.com",
    "size": 1000000,
    "larger": "10M",
    "smaller": "10M",
    "id": "ALongRandomStringOfCharactersNumbersAndOtherChars-+@mail.gmail.com",
    "has": "yellow-star"
}
messages = gmail.get_messages(query=construct_query(query_params))
```

### CODE REVIEW

**Comment by jeremyephron** [comment]
Hey @rasa, really appreciate all your efforts to improve this package! Sorry I am and have been so busy with (my primary) work, that I can't get to these sooner, but your PRs (and other existing ones) are not forgotten and I will try to get to them in the near future.

**Comment by linkyndy** [comment]
@jeremyephron, what is the status of this repo? I see a lot of PRs pending for quite some time now. I also found a few missing things and would like to start opening a few PRs. Is it worth the effort? Is this repo still maintained? Thanks! 🙏

**Comment by jeremyephron** [comment]
@linkyndy Ah this breaks my heart. I am immensely busy and work nearly 24/7, a _fortunate_ reality, as I am lucky and love what I'm working on, but _unfortunate_ for things like this package that get cast aside as lower priority. Let me see if I can block off time this Saturday to maintain this package. If I do not get to anything on Saturday, I recommend losing hope and not contributing. If I get to some things on Saturday, keep the fire alive.

**Comment by linkyndy** [comment]
@jeremyephron by no chance I wanted to put any pressure on you. This project shouldn't stay between you and a sane work-life balance 🙏 

I see some pretty valuable PRs already opened, which I don't think require too much tinkering besides merging and releasing a new library version. Alternatively, have you considered expanding the maintainer rights of the repo, so that other people can back you up? Things look really solid in here and it would be a shame if development stopped.

**Comment by jeremyephron** [comment]
@rasa Thanks for contributing this. The commit has been merged. You can see the edits I made in the following commit: 29bd7dedef05dd4f4b0436841d87d25b80fd0fb8.

I do not use, and generally dislike, Github's PR system, so I merge things using git on the command line. Your commit has been merged but Github does not recognize that this PR has been merged because the commit was rebased, so I am closing.

**Pull request closed without merging**
